apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.image.name | lower }}-{{ .Values.service.type | lower }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.targetPort }}{{ .Values.service.protocol | lower }}
      port: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: "{{ .Release.Name }}-{{ .Values.image.name }}"
    release: {{ .Release.Name }}