apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.image.name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{ include "jobo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.image.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Values.image.name }}"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Values.image.name }}"
        release: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: {{ .Values.service.targetPort }}{{ .Values.service.protocol | lower }}
          protocol: {{ .Values.service.protocol }}
        volumeMounts:
        - mountPath: {{ .Values.configMap.mountPath }}
          name: configmap
        - mountPath: {{ .Values.ldapConf.mountPath }}
          name: ldapconf
        - mountPath: /var/www/html/version/
          name: version
      {{- if .Values.image.deployRegistry }}
      imagePullSecrets:
      - name: "{{ .Values.image.name }}-{{ .Values.image.imagePullSecrets }}"
      {{- end }}
      volumes:
      - name: configmap
        secret:
          defaultMode: 511
          items:
          - key: conf.php
            path: conf.php
          - key: conf_cifs.json
            path: conf_cifs.json
          optional: false
          secretName: config-{{ .Values.image.name }}
      - name: ldapconf
        secret:
          defaultMode: 511
          items:
          - key: {{ .Values.ldapConf.key }}
            path: {{ .Values.ldapConf.key }}
          optional: false
          secretName: ldap-{{ .Values.image.name }}
      - name: version
        configMap:
          defaultMode: 0777
          items:
          - key: version.json
            path: ./version.json
          name: "{{ .Release.Name }}-version"
