{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.image.name  }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.image.name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: "{{ .Values.ingress.url }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.service.type | lower }}
              servicePort: {{ .Values.service.targetPort }}{{ .Values.service.protocol | lower }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}