{{- if .Values.deploySecret -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.imagePullSecrets }}
  namespace: {{ .Release.Namespace  }}
data:
  .dockerconfigjson: {{ .Values.dataSecret }}
{{- end -}}
