apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.type | lower }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.targetPort }}{{ .Values.service.protocol | lower }}
      port: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}